### ISSUE TITLE
babylon raises an unknown SyntaxError

### ISSUE THREAD

**Issue by kjirou** [kjirou/developers-defense#22]
When I try to use the `babel-plugin-jsdoc-to-assert`, the `babylon` raises an error.

----

```bash
npm install -D babel-plugin-jsdoc-to-assert
```

And, modify the `gulpfile.js` like this:

```
105 const bundleJsSources = (bundler, options) => {
106   options = Object.assign({
107     errorHandler: function(err) {
108       // For debugging of the babylon
109       console.log(err.codeFrame);
110       throw err;
111     },
112     outputFileName: `${ APP_NAME }.js`,
113   }, options || {});
114   
```

　↓

Execute `gulp build:js`

```bash
gulp build:js
[14:27:43] Starting 'build:js'...
> 1 | const { ACTION_TYPES, BOARD_TYPES, FACTION_TYPES, PARAMETERS } = require('../immutable/constants');
    |                                                                                             ^
  2 | const { JOB_IDS } = require('../immutable/jobs');
  3 | const { findOneSquareFromBoardsByPlacement } = require('../state-models/complex-apis');
  4 | const { areSamePlace, isPlacedOnBoard } = require('../state-models/placement');
/Users/kjirou/app/developers-defense/gulpfile.js:109
      throw err;
      ^

SyntaxError: Unexpected token, expected , (1:92)
    at Parser.pp$5.raise (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:1627:8)
    at Parser.pp.expect (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:1615:33)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:3646:12)
    at Parser.pp$3.parseExprAtom (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:3545:19)
    at Parser.pp$3.parseExprSubscripts (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:3331:19)
    at Parser.pp$3.parseMaybeUnary (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (/Users/kjirou/app/developers-defense/node_modules/babylon/lib/index.js:3181:19)from
    at exports.default (/Users/kjirou/app/developers-defense/node_modules/babel-template/lib/index.js:12:11)
    at injectParameterAssert (/Users/kjirou/app/developers-defense/node_modules/babel-plugin-jsdoc-to-assert/lib/index.js:57:23)
    at PluginPass.ArrowFunctionExpressionVariableDeclaration (/Users/kjirou/app/developers-defense/node_modules/babel-plugin-jsdoc-to-assert/lib/index.js:107:11)
    at newFn (/Users/kjirou/app/developers-defense/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/kjirou/app/developers-defense/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/kjirou/app/developers-defense/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/kjirou/app/developers-defense/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/kjirou/app/developers-defense/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/kjirou/app/developers-defense/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/kjirou/app/developers-defense/node_modules/babel-traverse/lib/context.js:190:19)
```

**Comment by kjirou** [comment]
I decided to use `flow` instead of `jsdoc-to-assert`.
